### ISSUE TITLE
Detection discrepancies

### ISSUE THREAD

**Issue by charlesverge** [chefkoch-dev/morphoji#9]
I've noted a few discrepancies when testing your library, https://github.com/charlesverge/emoji-php-comparsion  The following two emoji come up as not emoji but are listed as emoji in https://github.com/milesj/emoji-database/
            ©︎
            ®︎

It's debatable if those are emoji or not depending on the use case. This is for the most part an none issue but wanted to let you know of my test results.

**Comment by nem75** [comment]
Thanks for the input!

While it's debatable (as you pointed out) if these should be categorized as emoji or not, they are definitely not 4 byte unicode, which is the focus of the library.
